### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by GreenForzeGaming**
new enhanced textures for framed tools

### CODE REVIEW

**Comment by XFactHD** [comment]
Thank you very much for the new textures.

I have finally tried them in-game (for some reason I didn't think about doing this earlier) and the Framed Hammer, Framed Screwdriver and Framed Key look great. The Framed Wrench, while it's a cool design, looks weird in-game, mainly because it points in the wrong direction (left side). Flipping the texture unfortunately doesn't really help either and still looks weird, mainly on the bottom edge of the wrench (right side):

(Ignore the small gaps on the item models, that's just Minecraft being weird).
I think the easiest solution would be to go back to the simple straight design I used but if you have a better idea then I'd be very interested to see it.

PS: to add more changes to this Pull Request, you just add the additional changes to your fork the same way you added the new textures and they will show up in this Pull Request.

**Comment by GreenForzeGaming** [comment]
Sure!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by XFactHD** [comment]
Thank you very much, now I'm fully happy with the new textures.
I'll merge them into 1.19 and then manually backport them to 1.18 and release them with the next update.

**Comment by GreenForzeGaming** [comment]
No problem!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
